#!/usr/bin/env python3
"""Generate the model-constants header for a ggml adapter target from its
binding's host_params section.

The binding yaml is the single source for every model-specific constant in
the window code; the generated header is checked in next to the window
translation unit (regenerate after editing the binding):

    python3 tools/gen_binding_header.py llamacpp_qwen36_35b_sm120
"""

from __future__ import annotations

import pathlib
import sys

import yaml

_HERE = pathlib.Path(__file__).resolve().parent
_REPO = _HERE.parents[2]
_BINDINGS = _REPO / "flash_rt" / "catalog" / "bindings"


def main() -> None:
    name = sys.argv[1] if len(sys.argv) > 1 else "llamacpp_qwen36_35b_sm120"
    data = yaml.safe_load((_BINDINGS / f"{name}.yaml").read_text())
    hp = data["host_params"]

    lines: list[str] = []
    a = lines.append
    a("// Generated by tools/gen_binding_header.py from")
    a(f"// flash_rt/catalog/bindings/{name}.yaml — edit the binding, not this file.")
    a("#pragma once")
    a("")
    a("namespace frt_binding {")
    a("")
    a(f"constexpr int n_layer        = {hp['n_layer']};")
    a(f"constexpr int layer_scan_max = {hp['layer_scan_max']};")
    a(f"constexpr int d_model        = {hp['d_model']};")
    a("")
    a("// fused qkv_pack regions (kind-indexed)")
    a("struct region_member { const char * name; int rows; int off; bool leader; };")
    regions = hp["regions"]
    n_kinds = len(regions)
    max_members = max(len(r["members"]) for r in regions)
    a(f"constexpr int n_region_kinds = {n_kinds};")
    a(f"constexpr int region_max_members = {max_members};")
    layers = ", ".join(str(r["layers"]) for r in regions)
    ks = ", ".join(str(r["k"]) for r in regions)
    ns = ", ".join(str(sum(m["rows"] for m in r["members"])) for r in regions)
    counts = ", ".join(str(len(r["members"])) for r in regions)
    a(f"constexpr int region_layers[{n_kinds}]    = {{{layers}}};")
    a(f"constexpr int region_k[{n_kinds}]         = {{{ks}}};")
    a(f"constexpr int region_n[{n_kinds}]         = {{{ns}}};   // sum of member rows")
    a(f"constexpr int region_n_members[{n_kinds}] = {{{counts}}};")
    a(f"constexpr region_member region_members[{n_kinds}][{max_members}] = {{")
    for r in regions:
        row = []
        for m in r["members"]:
            leader = "true" if m.get("leader") else "false"
            row.append(f'{{"{m["name"]}", {m["rows"]}, {m["row_off"]}, {leader}}}')
        while len(row) < max_members:
            row.append("{nullptr, 0, 0, false}")
        a("    {" + ", ".join(row) + "},")
    a("};")
    a("")
    g = hp["gdn"]
    a("// gated_delta_core instance dims")
    a(f"constexpr int gdn_qkvz_rows      = {g['qkvz_rows']};")
    a(f"constexpr int gdn_qkv_rows       = {g['qkv_rows']};")
    a(f"constexpr int gdn_z_rows         = {g['z_rows']};")
    a(f"constexpr int gdn_conv_channels  = {g['conv_channels']};")
    a(f"constexpr int gdn_conv_window    = {g['conv_window']};")
    a(f"constexpr int gdn_conv_cache_row = {g['conv_cache_row']};")
    a(f"constexpr int gdn_state_size     = {g['state_size']};")
    a(f"constexpr int gdn_out_dim        = {g['out_dim']};")
    a(f"constexpr int gdn_head_dim       = {g['head_dim']};")
    a("")
    m = hp["moe"]
    a("// moe_expert_ffn instance (dims are read from tensors at run time)")
    a(f'constexpr const char * moe_gate_exps      = "{m["gate_exps"]}";')
    a(f'constexpr const char * moe_up_exps        = "{m["up_exps"]}";')
    a(f'constexpr const char * moe_down_exps      = "{m["down_exps"]}";')
    a(f'constexpr const char * moe_gate_shexp     = "{m["gate_shexp"]}";')
    a(f'constexpr const char * moe_up_shexp       = "{m["up_shexp"]}";')
    a(f'constexpr const char * moe_down_shexp     = "{m["down_shexp"]}";')
    a(f'constexpr const char * moe_gate_inp_shexp = "{m["gate_inp_shexp"]}";')
    a(f"constexpr int moe_n_expert = {m['n_expert']};")
    a(f'constexpr const char * moe_draft_prefix = "{m["draft_prefix"]}";')
    outs = ", ".join(f'"{n}"' for n in m["out_names"])
    resids = ", ".join(f'"{n}"' for n in m["resid_names"])
    a(f"constexpr const char * moe_out_names[{len(m['out_names'])}]   = {{{outs}}};")
    a(f"constexpr const char * moe_resid_names[{len(m['resid_names'])}] = {{{resids}}};")
    a("")
    o = hp["out_proj"]
    names = ", ".join(f'"{n}"' for n in o["names"])
    a("// out-proj linear_proj instances")
    a(f"constexpr const char * out_proj_names[{len(o['names'])}] = {{{names}}};")
    a(f"constexpr int out_proj_k = {o['k']};")
    a("")
    h = hp["head"]
    a("// lm head")
    a(f'constexpr const char * head_name = "{h["name"]}";')
    a(f"constexpr int head_n_vocab = {h['n_vocab']};")
    a("")
    a("} // namespace frt_binding")
    a("")

    out = _HERE.parent / f"fr_binding_{name.split('llamacpp_')[-1]}.h"
    out.write_text("\n".join(lines))
    print(f"wrote {out} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
